### ISSUE TITLE
Incompatible with Python 3

### ISSUE THREAD

**Issue by jeremyvisser** [casebeer/afsk#8]
The AFSK library doesn't load properly when I run it on my Fedora 30 system with Python 3.7.

Some of the issues that occur:

```
>>> import afsk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/afsk/__init__.py", line 2, in <module>
    from afsk import encode
ImportError: cannot import name 'encode' from 'afsk' (/usr/local/lib/python3.7/site-packages/afsk/__init__.py)
```

I experienced further errors in the 'audiogen' library, but it appears these have already been reported in https://github.com/casebeer/audiogen/issues/2.

**Comment by janesmae** [comment]
+1
